export default {
  hello: "Hello",
  start: "Time to make a decision",
  languageSelector: "Select language",
  createGame: "Create a game",
  joinGame: "Join a game",
  doneGames: "Finished games",
  settings: "Settings",
  cancel: "Cancel",
  logout: "Sign out",
  changePassword: "Change password",
  deleteAccount: "Delete account",
  pp: "Privacy policy",
  male: "Male",
  female: "Female",
  hours: "Weeks in game",
  count: "Number of completed games",
  chooseInfo: "Choose what information will be shown in your profile",
  about: "Something about you...",
  done: "Done",
  auth: "Authorization",
  email: "Email",
  password: "Password",
  login: "Sign In",
  signUp: "Sing Up",
  register: "Registration",
  repeatPassword: "Repeat password",
  nick: "Username",
  doLogin: "Sign In",
};
