export default {
  hello: "Привет",
  start: "Пора сделать выбор",
  languageSelector: "Выберите язык",
  createGame: "Создать игру",
  joinGame: "Присоединиться к игре",
  doneGames: "Завершено игр",
  settings: "Настройки",
  cancel: "Отмена",
  logout: "Выйти",
  changePassword: "Сменить пароль",
  deleteAccount: "Удалить аккаунт",
  pp: "Политика конфиденциальности",
  male: "Мужской",
  female: "Женский",
  hours: "Количество недель в игре",
  count: "Количество законченных игр",
  chooseInfo: "Выбери, какая информация будет отображаться в твоём профиле",
  about: "Немного о себе...",
  done: "Готово",
  auth: "Авторизация",
  email: "Почта",
  password: "Пароль",
  login: "Войти",
  signUp: "Зарегистрироваться",
  register: "Регистрация",
  repeatPassword: "Повторите пароль",
  nick: "Ник",
  doLogin: "Войти в аккаунт",
};
